<center>
    <img src="https://rockborne.com/wp-content/uploads/2021/07/LandingPage-Header-RED-CENTRE.jpg" width="900" alt="logo"  />
</center>

# Practical Pandas: San Francisco Salaries (Coach Version)

## About this notebook
A hands-on lab that puts the **Pandas Walkthrough** skills to work on a single, real-world table: the **San Francisco municipal salaries** dataset (about 148,654 rows). You'll practise exploring, selecting, sorting, filtering, creating columns, aggregating with `groupby`, and even a realistic join, all while answering practical questions about who gets paid what.

## About the exercises
Each exercise is made of three cells:

1. **The question** (a markdown cell like this one).
2. **`# Your turn`**: an empty code cell for you to attempt the solution.
3. **`# Coach answer`**: the worked solution with correct code.

Try each one yourself first. Later exercises reuse variables from earlier ones, so work in order.

> **Coach note:** this is the *coach version*, so every answer is filled in and the notebook runs top-to-bottom with `Run All`. To produce the learner version, delete the `# Coach answer` cells.

## About the data
`Salaries.csv` lives one folder up from this notebook, in [`../datasets/`](../datasets/). Key columns: `EmployeeName`, `JobTitle`, `BasePay`, `OvertimePay`, `OtherPay`, `Benefits`, `TotalPay`, `TotalPayBenefits`, `Year`. Source: the [SF Salaries dataset](https://www.kaggle.com/kaggle/sf-salaries) on Kaggle.

> A companion notebook in the next module revisits this same data from a **data-quality** angle (missing values, suspicious pay, redundant columns).

---
# Part 0: Setup and loading the data

The data sits **one directory above** this notebook, so the path starts with `../`.

In [2]:
import pandas as pd

### Exercise 0: Load the salaries file

Read `../datasets/Salaries.csv` into a DataFrame called `sal`, then show the first 5 rows.

> *Hint: `pd.read_csv(path)` loads a CSV; `.head()` previews the first rows.*

In [ ]:
# Your turn. Write your solution here:
sal = pd.read_csv('https://rockborne-bucket-01-cbs.s3.eu-west-2.amazonaws.com/Data_Sources_CBS_Risk/Salaries.csv')
sal.head()

In [ ]:
"""

sal = (
    spark.read.csv(
        "s3a://rockborne-bucket-01-cbs/Data_Sources_CBS_Risk/Salaries.csv",
        header=True,
        inferSchema=True
    )
).toPandas()

sal.head()

"""

In [4]:
# Coach answer
#Local files
#sal = pd.read_csv('../datasets/Salaries.csv')
#S3:
sal = pd.read_csv('https://rockborne-bucket-01-cbs.s3.eu-west-2.amazonaws.com/Data_Sources_CBS_Risk/Salaries.csv')
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

---
# Part 1: Explore the data

### Exercise 1.1: First look

Show the first 5 rows of `sal`.

In [4]:
# Your turn. Write your solution here:

In [5]:
# Coach answer
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

### Exercise 1.2: How big is it?

How many rows (entries) and columns does `sal` have? Use one method that also shows each column's non-null count and dtype.

> *Hint: `.info()` reports row count, columns, dtypes and non-null counts at once.*

In [6]:
# Your turn. Write your solution here:

In [7]:
# Coach answer
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

### Exercise 1.3: Columns and types

List the column names, then show the data type of each column.

In [8]:
# Your turn. Write your solution here:

In [9]:
# Coach answer
print(sal.columns.tolist())
sal.dtypes

['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay', 'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency', 'Status']

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

### Exercise 1.4: Summary statistics

Get count, mean, std, min, quartiles and max for the numeric columns in one call.

> *Hint: `.describe()` summarises numeric columns.*

In [10]:
# Your turn. Write your solution here:

In [11]:
# Coach answer
sal.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,148654.000000,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000,0.0,0.0
mean,74327.500000,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643,NaN,NaN
std,42912.857795,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538,NaN,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN,NaN
25%,37164.250000,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000,NaN,NaN
50%,74327.500000,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000,NaN,NaN
75%,111490.750000,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000,NaN,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN,NaN

---
# Part 2: Selecting columns and sorting

### Exercise 2.1: Select a few columns

Create a view with only `EmployeeName`, `JobTitle` and `TotalPayBenefits`.

> *Hint: Multiple columns go inside a *list*: `df[['a', 'b']]`.*

In [12]:
# Your turn. Write your solution here:

In [13]:
# Coach answer
sal[['EmployeeName', 'JobTitle', 'TotalPayBenefits']].head()

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),335279.91
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,332343.61
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",326373.19

### Exercise 2.2: Top 10 earners

Show the 10 highest-paid people by `TotalPayBenefits` (name, job title and pay).

> *Hint: `sort_values('col', ascending=False)` then `.head(10)`.*

In [14]:
# Your turn. Write your solution here:

In [15]:
# Coach answer
(sal.sort_values('TotalPayBenefits', ascending=False)
    [['EmployeeName', 'JobTitle', 'TotalPayBenefits']]
    .head(10))

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),538909.28
110531,David Shinn,Deputy Chief 3,510732.68
110532,Amy P Hart,Asst Med Examiner,479652.21
110533,William J Coaker Jr.,Chief Investment Officer,436224.36
72925,Gregory P Suhr,Chief of Police,425815.28
72926,Joanne M Hayes-White,"Chief, Fire Department",422353.40
110534,Gregory P Suhr,Chief of Police,418019.22
110535,Joanne M Hayes-White,"Chief, Fire Department",417435.10
110536,Ellen G Moffatt,Asst Med Examiner,415767.94

### Exercise 2.3: The lowest paid

Show the 5 lowest values of `TotalPayBenefits`. Notice anything odd about the smallest values?

> *Hint: Sort ascending (the default) and look at the head. Some values are zero or negative.*

In [16]:
# Your turn. Write your solution here:

In [17]:
# Coach answer
(sal.sort_values('TotalPayBenefits')
    [['EmployeeName', 'JobTitle', 'TotalPayBenefits']]
    .head(5))

            EmployeeName                    JobTitle  TotalPayBenefits
148653         Joe Lopez  Counselor, Log Cabin Ranch           -618.13
110530     David P Kucia            Police Officer 3            -33.89
110529    Mark E Laherty            Police Officer 3             -8.20
110528  Timothy E Gibson            Police Officer 3             -2.73
148633  Edward Ferdinand             General Laborer              0.00

### Exercise 2.4: Rename columns

Some people prefer snake_case. Create a **new** DataFrame `sal_snake` where `EmployeeName` becomes `employee_name` and `JobTitle` becomes `job_title` (leave `sal` unchanged).

> *Hint: `df.rename(columns={'old': 'new'})` returns a new DataFrame when you don't pass `inplace=True`.*

In [18]:
# Your turn. Write your solution here:

In [19]:
# Coach answer
sal_snake = sal.rename(columns={'EmployeeName': 'employee_name', 'JobTitle': 'job_title'})
sal_snake.columns.tolist()

['Id',
 'employee_name',
 'job_title',
 'BasePay',
 'OvertimePay',
 'OtherPay',
 'Benefits',
 'TotalPay',
 'TotalPayBenefits',
 'Year',
 'Notes',
 'Agency',
 'Status']

---
# Part 3: Filtering rows

### Exercise 3.1: Find a person's job

What is the job title of `JOSEPH DRISCOLL`? (Use all caps: there's also a lowercase entry.)

In [20]:
# Your turn. Write your solution here:

In [21]:
# Coach answer
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

### Exercise 3.2: And their total pay

How much does `JOSEPH DRISCOLL` make in total, including benefits?

In [22]:
# Your turn. Write your solution here:

In [23]:
# Coach answer
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### Exercise 3.3: Highest paid, with `.loc`

Use `.loc` together with `idxmax()` to pull the full row of the highest-paid person.

> *Hint: `idxmax()` gives the index label of the maximum; `.loc[label]` selects that row.*

In [24]:
# Your turn. Write your solution here:

In [25]:
# Coach answer
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

### Exercise 3.4: Combine two conditions

How many people earned more than 200,000 in `TotalPayBenefits` in the year 2013?

> *Hint: Combine conditions with `&`, wrap each in parentheses, then `.sum()` counts the `True`s.*

In [26]:
# Your turn. Write your solution here:

In [27]:
# Coach answer
mask = (sal['Year'] == 2013) & (sal['TotalPayBenefits'] > 200000)
mask.sum()

np.int64(2852)

### Exercise 3.5: Text search with `.str.contains`

How many rows have the word `Police` anywhere in their job title (any capitalisation)?

> *Hint: `.str.contains('police', case=False)` returns a boolean Series.*

In [28]:
# Your turn. Write your solution here:

In [29]:
# Coach answer
sal['JobTitle'].str.contains('police', case=False).sum()

np.int64(8201)

### Exercise 3.6: Filter by a list with `.isin`

How many rows have one of these exact job titles: `Firefighter`, `Police Officer 3`, `Registered Nurse`?

> *Hint: `.isin([...])` checks membership against a list.*

In [30]:
# Your turn. Write your solution here:

In [31]:
# Coach answer
titles = ['Firefighter', 'Police Officer 3', 'Registered Nurse']
sal['JobTitle'].isin(titles).sum()

np.int64(8516)

---
# Part 4: Creating columns

### Exercise 4.1: Rebuild and check TotalPay

Create a column `pay_check` equal to `BasePay + OvertimePay + OtherPay`. Does it match the existing `TotalPay`? Show how many rows differ by more than 1 cent.

> *Hint: Add the three columns, then compare to `TotalPay` with an absolute difference.*

In [32]:
# Your turn. Write your solution here:

In [33]:
# Coach answer
sal['pay_check'] = sal['BasePay'] + sal['OvertimePay'] + sal['OtherPay']
(
    (sal['pay_check'] - sal['TotalPay']).abs() > 0.01
).sum()

np.int64(0)

### Exercise 4.2: An overtime ratio

Create a column `overtime_ratio` = `OvertimePay / TotalPay`, then describe it. What's a typical value?

> *Hint: Most people do little overtime, so the median is near zero.*

In [34]:
# Your turn. Write your solution here:

In [35]:
# Coach answer
sal['overtime_ratio'] = sal['OvertimePay'] / sal['TotalPay']
sal['overtime_ratio'].describe()

count    1.482860e+05
mean     4.916493e-02
std      8.997878e-02
min     -1.305943e-07
25%      0.000000e+00
50%      0.000000e+00
75%      6.127783e-02
max      3.000458e+00
Name: overtime_ratio, dtype: float64

### Exercise 4.3: Flag the chiefs with `.apply`

How many people have the word `chief` somewhere in their job title? Write a function and use `.apply()`.

> *Hint: Define a function returning True/False, then `.apply()` it and `.sum()` the result.*

In [36]:
# Your turn. Write your solution here:

In [37]:
# Coach answer
def has_chief(title):
    return 'chief' in title.lower()

sal['JobTitle'].apply(has_chief).sum()

np.int64(627)

---
# Part 5: Aggregating with `groupby`

### Exercise 5.1: Average base pay

What is the average `BasePay` across everyone?

In [38]:
# Your turn. Write your solution here:

In [39]:
# Coach answer
sal['BasePay'].mean()

np.float64(66325.44884048769)

### Exercise 5.2: Biggest overtime

What is the highest single `OvertimePay` value?

In [40]:
# Your turn. Write your solution here:

In [41]:
# Coach answer
sal['OvertimePay'].max()

245131.88

### Exercise 5.3: Distinct job titles

How many unique job titles are there?

In [42]:
# Your turn. Write your solution here:

In [43]:
# Coach answer
sal['JobTitle'].nunique()

2159

### Exercise 5.4: Most common jobs

What are the 5 most common job titles?

In [44]:
# Your turn. Write your solution here:

In [45]:
# Coach answer
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

### Exercise 5.5: Average base pay per year

Use `groupby` to find the mean `BasePay` for each `Year`.

In [46]:
# Your turn. Write your solution here:

In [47]:
# Coach answer
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

### Exercise 5.6: Several stats per year at once

For each `Year`, compute the mean `BasePay`, the mean `TotalPayBenefits`, and the headcount (number of records).

> *Hint: `groupby('Year').agg(new=(col, func), ...)` builds several aggregates in one go.*

In [48]:
# Your turn. Write your solution here:

In [49]:
# Coach answer
sal.groupby('Year').agg(
    mean_base=('BasePay', 'mean'),
    mean_total=('TotalPayBenefits', 'mean'),
    headcount=('Id', 'count'),
)

         mean_base     mean_total  headcount
Year
2011  63595.956517   71744.103871      36159
2012  65436.406857  100553.229232      36766
2013  69630.030216  101440.519714      37606
2014  66564.421924  100250.918884      38123

### Exercise 5.7: Top-paying job titles

Among job titles held by at least 50 people, which 5 have the highest average `TotalPayBenefits`?

> *Hint: First find the titles with >= 50 holders, filter to them with `.isin`, then group and sort.*

In [50]:
# Your turn. Write your solution here:

In [51]:
# Coach answer
counts = sal['JobTitle'].value_counts()
common = counts[counts >= 50].index
(
    sal[sal['JobTitle'].isin(common)]
    .groupby('JobTitle')['TotalPayBenefits'].mean()
    .sort_values(ascending=False)
    .head(5)
)

JobTitle
Battalion Chief, Fire Suppress    306954.552769
Captain 3                         263116.498416
Captain, Fire Suppression         250041.297156
Dep Dir V                         248208.813600
Manager VIII                      244888.905634
Name: TotalPayBenefits, dtype: float64

### Exercise 5.8: Rare job titles

How many job titles were held by only one person in 2013?

> *Hint: Count the occurrences of each title in 2013, then count how many equal 1.*

In [52]:
# Your turn. Write your solution here:

In [53]:
# Coach answer
(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1).sum()

np.int64(202)

---
# Part 6: A small join (comparing pay to a yearly benchmark)

This dataset is a single table, so there's no second table to join to out of the box. But joins are everywhere in real work, so here's a realistic one. We'll bring in a tiny **reference table** holding one external figure per year, the approximate **San Francisco median household income**, and join it on `Year`. That lets us ask how city salaries compared to a typical household's income each year. Run the lookup cell first.

In [54]:
# A small reference table: one external figure per year.
# (Approximate SF median household income, in dollars.)
benchmark = pd.DataFrame({
    'Year': [2011, 2012, 2013, 2014],
    'sf_median_income': [71304, 73012, 75604, 78378],
})
benchmark

   Year  sf_median_income
0  2011             71304
1  2012             73012
2  2013             75604
3  2014             78378

### Exercise 6.1: Join the benchmark onto the salaries

Merge `benchmark` onto `sal` with a left join on `Year`. Call the result `sal_bench` and confirm it now has an `sf_median_income` column.

> *Hint: `pd.merge(left, right, on='Year', how='left')`.*

In [55]:
# Your turn. Write your solution here:

In [56]:
# Coach answer
sal_bench = pd.merge(sal, benchmark, on='Year', how='left')
sal_bench[['EmployeeName', 'Year', 'TotalPayBenefits', 'sf_median_income']].head()

        EmployeeName  Year  TotalPayBenefits  sf_median_income
0     NATHANIEL FORD  2011         567595.43             71304
1       GARY JIMENEZ  2011         538909.28             71304
2     ALBERT PARDINI  2011         335279.91             71304
3  CHRISTOPHER CHONG  2011         332343.61             71304
4    PATRICK GARDNER  2011         326373.19             71304

### Exercise 6.2: Compare each salary to the benchmark

Add a column `pay_vs_median` = `TotalPayBenefits / sf_median_income`, then show the average ratio per `Year`. A value of 2.0 would mean the average city salary was twice a typical household's income that year.

> *Hint: divide the two columns to build the ratio, then `groupby('Year')` and take the mean.*

In [57]:
# Your turn. Write your solution here:

In [58]:
# Coach answer
sal_bench['pay_vs_median'] = sal_bench['TotalPayBenefits'] / sal_bench['sf_median_income']
sal_bench.groupby('Year')['pay_vs_median'].mean().round(2)

Year
2011    1.01
2012    1.38
2013    1.34
2014    1.28
Name: pay_vs_median, dtype: float64

---
# Part 7: Tidying up and exporting

### Exercise 7.1: Drop columns you won't use

The `Notes` and `Status` columns aren't useful here. Create `sal_tidy` without them (keep `sal` intact). The *why* behind these empty columns is explored in the data-quality notebook next module.

> *Hint: `df.drop(columns=[...])` returns a new DataFrame when you don't pass `inplace=True`.*

In [59]:
# Your turn. Write your solution here:

In [60]:
# Coach answer
sal_tidy = sal.drop(columns=['Notes', 'Status'])
sal_tidy.columns.tolist()

['Id',
 'EmployeeName',
 'JobTitle',
 'BasePay',
 'OvertimePay',
 'OtherPay',
 'Benefits',
 'TotalPay',
 'TotalPayBenefits',
 'Year',
 'Agency',
 'pay_check',
 'overtime_ratio']

### Exercise 7.2: Export a yearly summary

Build a per-year summary (mean base pay, mean total pay, headcount) and save it to `../datasets/sf_salary_summary.csv`.

> *Hint: `groupby(...).agg(...)` to build it, then `.to_csv(path)`.*

In [61]:
# Your turn. Write your solution here:

In [62]:
# Coach answer
summary = sal.groupby('Year').agg(
    mean_base=('BasePay', 'mean'),
    mean_total=('TotalPayBenefits', 'mean'),
    headcount=('Id', 'count'),
)
summary.to_csv('../datasets/sf_salary_summary.csv')
summary

         mean_base     mean_total  headcount
Year
2011  63595.956517   71744.103871      36159
2012  65436.406857  100553.229232      36766
2013  69630.030216  101440.519714      37606
2014  66564.421924  100250.918884      38123

---
# Bonus: just for fun
These are trickier. Don't worry if you don't get them.

### Exercise B.1: Does a longer job title mean more pay?

Create a column `title_len` (the number of characters in `JobTitle`) and check whether it correlates with `TotalPayBenefits`.

> *Hint: `.apply(len)` gives the string length; `.corr()` gives the correlation matrix.*

In [63]:
# Your turn. Write your solution here:

In [64]:
# Coach answer
sal['title_len'] = sal['JobTitle'].apply(len)
sal[['title_len', 'TotalPayBenefits']].corr().iloc[0, 1]

np.float64(-0.03687844593260901)

---
## Further practice

- Try the same questions on a different dataset (NYC salaries, UK Census).
- Build a small report that summarises pay trends per year.
- Continue to the **data-quality** companion notebook to investigate the missing values and odd pay figures you spotted here.